version: "3.6"

services:
  keycloak:
    image: trifork/keycloak-smart-auth:1.0.0
    ports:
      - "8081:8080"
    environment:
      KEYCLOAK_USER: "admin"
      KEYCLOAK_PASSWORD: "admin"
      KEYCLOAK_FRONTEND_URL: "http://localhost:8081/auth/"
      DB_VENDOR: "postgres"
      DB_ADDR: "db"
      DB_USER: "keycloak"
      DB_PASSWORD: "keycloak"
      KEYCLOAK_IMPORT: /tmp/realm.json
    volumes:
      - ./realm.json:/tmp/realm.json:ro
    depends_on:
      - db

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: "keycloak"
      POSTGRES_PASSWORD: "keycloak"
      POSTGRES_DB: "keycloak"
  
  fhir_db:
    image: postgres:13
    environment:
      POSTGRES_USER: "hapi"
      POSTGRES_PASSWORD: "hapi"
      POSTGRES_DB: "hapi_r4"

  fhir-server:
    image: trifork/hapi-fhir-starter-smart-auth:5.5.1
    ports:
     - "9090:8080"
    depends_on:
      - fhir_db
    environment:
       SPRING_APPLICATION_JSON: '{
        "spring.datasource.url"  : "jdbc:postgresql://fhir_db:5432/hapi_r4",
        "spring.datasource.driverClassName"  : "org.postgresql.Driver",
        "spring.datasource.username" : "hapi",
        "spring.datasource.password" : "hapi",
        "spring.autoconfigure.exclude" : "org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration",
        "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.PostgreSQLDialect"
         }'    

  secure-fhir-server:
    image: trifork/hapi-fhir-starter-smart-auth:5.5.1
    ports:
     - "8080:8080"
    depends_on:
      - fhir_db
    environment:
       SPRING_APPLICATION_JSON: '{
        "spring.datasource.url"  : "jdbc:postgresql://fhir_db:5432/hapi_r4",
        "spring.datasource.driverClassName"  : "org.postgresql.Driver",
        "spring.datasource.username" : "hapi",
        "spring.datasource.password" : "hapi",
        "spring.security.oauth2.resourceserver.jwt.jwk-set-uri" : "http://keycloak:8080/auth/realms/smart/protocol/openid-connect/certs",
        "spring.security.oauth2.resourceserver.jwt issuer-uri" : "http://keycloak:8080/auth/realms/smart",
        "spring.hapi.fhir.smart_enabled" : "true",
        "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.PostgreSQLDialect"
         }'
      
