version: "3.6"

services:
  keycloak:
    image: trifork/keycloak-smart-auth:1.0.0
    ports:
      - "8081:8080"
    environment:
      KEYCLOAK_USER: "admin"
      KEYCLOAK_PASSWORD: "admin"
      KEYCLOAK_FRONTEND_URL: "http://localhost:8081/auth/"
      DB_VENDOR: "postgres"
      DB_ADDR: "db"
      DB_USER: "keycloak"
      DB_PASSWORD: "keycloak"
      KEYCLOAK_IMPORT: /tmp/realm.json
    volumes:
      - ./realm.json:/tmp/realm.json:ro
    depends_on:
      - db

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: "keycloak"
      POSTGRES_PASSWORD: "keycloak"
      POSTGRES_DB: "keycloak"
